### ISSUE TITLE
[Question] hyperion-project

### ISSUE THREAD

**Issue by brindosch** [MaikelH/TIL#1]
Dear MaikelH,
i am a collaborator of the open source ambilight project "hyperion" and due to the point of a growing user/developer base we want to move from a personal github repository to a github organization. We searched for some names and gathered some thoughts. "hyperion-project" would be a great name. But that name is already in use. Due to point you are still active but it seams you don´t really used it the last 3 years. May you be able to "bestow" that name our project? I know this is a very big requests. But i just wanted to ask, we would really appreciate it.

Thank you for reading.

Best Regards
brindosch

Link to current repo https://github.com/tvdzwan

**Comment by MaikelH** [comment]
I am willing to change the name of the project, as far as I know there are also not any plans in the near future for it. There are some other people in the project and I need to ask them also. 

I will get back to you in a couple of days at most.

**Comment by brindosch** [comment]
Thank you very much!

**Comment by MaikelH** [comment]
So I spoke to the others and they were fine with me changing the name. I can change the name of this team, so that the _hyperion-project_ name is available again. That would probably be the easiest I think. Then you can make a team with this name, so you are the owner of it.

**Comment by brindosch** [comment]
We are deeply grateful for your (and your team) "offer". If a rename is working, why not :)
We will wait until you renamed it and create a new one.
Thank you - this is so kind!

**Comment by MaikelH** [comment]
Ok I renamed the hyperion project, so you can create a team with the hyperion project name :). 

Good luck with your project :)

**Comment by brindosch** [comment]
Thank you very much, you will be part of the announcement post :)
